class LexFloatStatusCodes:

    LF_OK = 0

    LF_FAIL = 1

    LF_E_PRODUCT_ID = 40

    LF_E_CALLBACK = 41

    LF_E_HOST_URL = 42

    LF_E_TIME = 43

    LF_E_INET = 44

    LF_E_NO_LICENSE = 45

    LF_E_LICENSE_EXISTS = 46

    LF_E_LICENSE_NOT_FOUND = 47

    LF_E_LICENSE_EXPIRED_INET = 48

    LF_E_LICENSE_LIMIT_REACHED = 49

    LF_E_BUFFER_SIZE = 50

    LF_E_METADATA_KEY_NOT_FOUND = 51

    LF_E_METADATA_KEY_LENGTH = 52

    LF_E_METADATA_VALUE_LENGTH = 53

    LF_E_FLOATING_CLIENT_METADATA_LIMIT = 54

    LF_E_METER_ATTRIBUTE_NOT_FOUND = 55

    LF_E_METER_ATTRIBUTE_USES_LIMIT_REACHED = 56

    LF_E_PRODUCT_VERSION_NOT_LINKED = 57

    LF_E_FEATURE_FLAG_NOT_FOUND = 58

    LF_E_IP = 60

    LF_E_CLIENT = 70

    LF_E_SERVER = 71

    LF_E_SERVER_TIME_MODIFIED = 72

    LF_E_SERVER_LICENSE_NOT_ACTIVATED = 73

    LF_E_SERVER_LICENSE_EXPIRED = 74

    LF_E_SERVER_LICENSE_SUSPENDED = 75

    LF_E_SERVER_LICENSE_GRACE_PERIOD_OVER = 76
