dist: xenial
language: python
python:
- '3.7'
script:
- echo "Deploying to pypi..."
before_deploy:
- python pre-publish.py
deploy:
  provider: pypi
  skip_cleanup: true
  skip_existing: true
  user: adnan-kamili
  password:
    secure: PFQirHl9UHihi+zkww+HhRrwENKKOx26DVB8pbMJh8k5xNHo0P06d8S+JLj2ILlV/5lpqoDxkmZw+BpNUPHhWCUuO5ntKLVU6mAOatUAijUambp9cs9y826oNrvsESR8hs6VWg2n8ZT4rnW3n6KCxfYgFWWM8Eh846Vi+9L46fmYesJbcaiO0ZklE7cL5Hxlkb8Zcm4hWk6du8vQbemcv5EBJN+RD/CyV1KVdUiKfNWkhD0zUYCQEpzkaqhGp+iAthuuQrHMClQySOeKA5Z+PlhtMMECUrfubvnYEqblHGP3qD129XAR3MbJtriWo0rNYxbg3I5JbnmTAyRouEsrFcQPjFzpWMUcYNMYwc2u03dkO09jVTkfoP0a/RjmnFyATzn8dy4+cnVDUW0mqpqKcAOWypa+CB26+LXtRenqkV2J0AtOUVCBawa+REKBjgNVIgROevon9MrIIuSUjczrnro5FeIInVypPOL0V/Cig+7elyWFLydrjOM45/A8AQv+PHqeca4TPE1z2/tc84vCwi/aE+0zUK0kreACzF+/aJYTTr2WNcmzV5HlUQytYyJnpXQ4lhiMEjaK5sDDDfOrIC3YaqefmHJQi+IfrebID5SOG/PiQ8dz7jjWL0RxO3MZqCOlBqvbDrlTAFcX0NHVbbXea/LgwJE5qakBFajHWI0=
  distributions: sdist bdist_wheel
  on:
    tags: true
  